In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.0.0'

In [3]:
import numpy as np

In [4]:
mylist = [1,2,3]

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
nested_list = [[1,2],[3,4],[5,6]]

In [7]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((4,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.linspace(0,100,7,dtype=int)

array([  0,  16,  33,  50,  66,  83, 100])

In [21]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(5)

array([0.01752249, 0.82270099, 0.49922735, 0.74674018, 0.867655  ])

In [36]:
np.random.rand(3,4)

array([[0.75129857, 0.69156974, 0.48511845, 0.1494309 ],
       [0.60238815, 0.23420032, 0.0459184 , 0.99255672],
       [0.22189856, 0.80920626, 0.25130125, 0.75301145]])

In [35]:
np.random.randn(5,5)

array([[ 1.03731258,  0.17775373,  0.14293665,  0.53670987, -0.05124772],
       [ 1.52508288,  0.39894441, -0.35679948,  1.25558441, -0.44580092],
       [-0.53073217, -0.50572594,  0.44749632,  0.56286524,  0.65327801],
       [ 0.05630915,  1.01693053, -0.43262404, -0.21237949,  0.69658049],
       [-0.28701164,  1.30176097,  0.01867523,  1.32042342,  0.29358031]])

In [34]:
np.random.randint(134,434434,(2,3))

array([[ 17794, 102677, 179504],
       [329604, 371774, 172871]])

In [39]:
np.random.seed(234234)
np.random.rand(5)

array([0.07516721, 0.64941456, 0.12632188, 0.64158743, 0.80218222])

In [38]:
np.random.rand(5)

array([0.6621219 , 0.91875859, 0.78017386, 0.72087919, 0.39779702])

In [40]:
arr = np.arange(25)

In [44]:
ranarr = np.random.randint(0,50,5)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [59]:
ranarr

array([44,  4, 46, 24, 48])

In [46]:
arr.shape

(25,)

In [47]:
ranarr.shape

(5,)

In [48]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
ranarr.max()

48

In [57]:
ranarr.min()

4

In [60]:
ranarr.argmax()

4

In [61]:
ranarr.argmin()

1

In [63]:
ranarr.dtype

dtype('int64')

In [64]:
arr.dtype

dtype('int64')