In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.0.0'

In [3]:
import numpy as np

In [4]:
mylist = [1,2,3]

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
nested_list = [[1,2],[3,4],[5,6]]

In [7]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((4,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.linspace(0,100,7,dtype=int)

array([  0,  16,  33,  50,  66,  83, 100])

In [21]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(5)

array([0.01752249, 0.82270099, 0.49922735, 0.74674018, 0.867655  ])

In [24]:
np.random.rand(3,4)

array([[0.04977876, 0.71451305, 0.29390238, 0.79398422],
       [0.99661094, 0.43277906, 0.6292008 , 0.61257766],
       [0.67909457, 0.45389251, 0.32056684, 0.2040203 ]])

In [ ]:
np.random.randn()